### ISSUE TITLE
README example asking for input causes errors

### ISSUE THREAD

**Issue by machawk1** [campbellr/smashrun-client#4]
In the README:
`code = input("Go to '%s' and authorize this application. Paste the provided code here:" % auth_url[0])`

Following the example and entering the string received from the URI "foobarbaz", Python 2.7 returns:

``` sh
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    codeX = input("Go to '%s' and authorize this application. Paste the provided code here:" % auth_url[0])
  File "<string>", line 1, in <module>
NameError: name 'foobarbaz' is not defined
```

This can remedied a couple ways. If you use `raw_input` in the example, it won't be compatible with Py3. `input()` in Py3 is aliased to `eval(raw_input())`. Another way would be a try-catch block to assign `input()` to `raw_input()`, which would work for both Py2 and Py3 but seems like overkill for a simple example.

**Comment by campbellr** [comment]
I think I'd be happy with changing it to `raw_input` and maybe adding a comment explaining that the user should use `input` in py3.

Thanks for testing!

**Comment by campbellr** [comment]
@machawk1 This should be fixed now.
