### ISSUE TITLE
count not respected for get_activities

### ISSUE THREAD

**Issue by nall** [campbellr/smashrun-client#5]
Hi,
If I specify a count of 2 for get_activities, I'd expect the iterator to return a total of 2 activities. Instead it still returns all activities -- it just paginates with 2 entries per page.

I think there should be a break in the loop in `_iter` if it's seen `count` items.

Thoughts? Am I just missing something?

**Comment by campbellr** [comment]
I'll admit that it is a bit unintuitive (in hindsight), but this is actually the name of the query parameter in the Smashrun API (https://api.smashrun.com/documentation)  that is used to indicate the number of results per page, and I was trying to stick as close to that API as possible.

That being said, there's no reason we couldn't add an additional keyword argument that does what you want (Something like `client.get_activities(max=2)`)

In the meantime, you could also use [itertools.islice](https://docs.python.org/2/library/itertools.html).

**Comment by nall** [comment]
Thanks. You can close this. I understand the issue.
