### ISSUE TITLE
The fromDate in searches should be local time, not UTC

### ISSUE THREAD

**Issue by nall** [campbellr/smashrun-client#6]
This wasn't intuitive to me, but the value passed to `fromDate` when searching activities should be local time, not UTC. 

You can read more on [this thread](http://discuss.smashrun.com/t/searching-fromdate-bug-or-my-confusion/100) on the SmashRun forums.

It sounds like they may expose a `fromDateUTC` argument that would be suitable for the value generated by `to_timestamp` in this library.

**Comment by campbellr** [comment]
Oh thanks for reporting this.

I think I just assumed that the fromDate was UTC without bothering to confirm...

I'll try to fix this and make a new release tonight.

**Comment by campbellr** [comment]
@nall I created a PR (#7) that I _think_ addresses this. I will merge it in in a few day if you don't have any objections.

**Comment by nall** [comment]
I verified with that change I can backout my current workaround. Looks good, thanks!
