### ISSUE TITLE
get_activites style is briefs, not brief

### ISSUE THREAD

**Issue by nall** [campbellr/smashrun-client#9]
In get_activities, you check that one of the valid styles is "brief", but it should be "briefs".

Using "brief" results in a error.

**Comment by campbellr** [comment]
Thanks.

In hindsight i don't think the validation is particularly useful to do on the client. If the user passes in a style that is invalid, they'll end up getting a 404 anyways.

So, I'll just remove it (but fix the documentation).

**Comment by nall** [comment]
Great, thanks!

Unrelated: it looks like they're going to add an ability to update runs soon. I'll probably take a crack at updating the client when they do (I need this functionality) and send you a pull request.
